#!/bin/sh
for i in /etc/rc.d/rcK.d/K??* ;do

    # Ignore dangling symlinks (if any).
    [ ! -f "$i" ] && continue

    case "$i" in
	*.sh )
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	* )
	    # No sh extension, so fork subprocess.
	    $i stop
	    ;;
    esac
done
