#!/bin/sh

mount -t proc proc /proc
mount -t tmpfs tmpfs /tmp
mount -t sysfs sysfs /sys
mount -t tmpfs mdev /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/rc.d/rcS.d/S??* ;do

    # Ignore dangling symlinks (if any).
    [ ! -f "$i" ] && continue

    case "$i" in
	*.sh )
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	* )
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done
