PREFIX_BIN := $(PJ_PREFIX)/bin
PREFIX_SBIN := $(PJ_PREFIX)/sbin
PREFIX_LIB := $(PJ_PREFIX)/lib
PREFIX_ETC := $(PJ_PREFIX)/etc
PREFIX_RC := $(PREFIX_ETC)/rc.d
PREFIX_INIT := $(PREFIX_RC)/init.d

ROOTFS_ETC := $(ROOTFS)/etc
ROOTFS_RC := $(ROOTFS_ETC)/rc.d
ROOTFS_RCS := $(ROOTFS_RC)/rcS.d
ROOTFS_RCK := $(ROOTFS_RC)/rcK.d
ROOTFS_INIT := $(ROOTFS_RC)/init.d
ROOTFS_DEV := $(ROOTFS)/dev
ROOTFS_LIB := $(ROOTFS)/lib
ROOTFS_MOD := $(ROOTFS_LIB)/modules
ROOTFS_BIN := $(ROOTFS)/bin
ROOTFS_SBIN := $(ROOTFS)/sbin
ROOTFS_VAR := $(ROOTFS)/var
ROOTFS_WWW := $(ROOTFS_VAR)/www
ROOTFS_PROC := $(ROOTFS)/proc
ROOTFS_OPT := $(ROOTFS)/opt
ROOTFS_USR := $(ROOTFS)/usr
ROOTFS_USR_BIN := $(ROOTFS_USR)/bin
ROOTFS_USR_SBIN := $(ROOTFS_USR)/sbin
ROOTFS_SYS := $(ROOTFS)/sys
ROOTFS_TMP := $(ROOTFS)/tmp

